# Generated by Django 4.2.2 on 2023-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckbrand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('subcatgeory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('images', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
