# Generated by Django 4.2.2 on 2023-07-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckbrand', '0003_alter_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
